### ISSUE TITLE
Add timestring module support

### ISSUE THREAD

**Issue by evanshortiss** [evanshortiss/expeditious#1]
Would be nice if the _defaultTtl_, and _ttl_ options could be provided as a format such as "1h 15m" or similar. This module can be used to achieve it: https://www.npmjs.com/package/timestring

**Comment by HackersSpirit** [comment]
@evanshortiss : can the issue be assigned to me

**Comment by evanshortiss** [comment]
Hi Satyam,

It would not be in the example since the issue applies to the actual
library code. I think somewhere around here would be the place:
https://github.com/evanshortiss/expeditious/blob/master/lib/handlers.js#L49
